### ISSUE TITLE
PHP 7?

### ISSUE THREAD

**Issue by champfish** [pluma-lms/pluma-lms#40]
PHP 7 was released today, should we use it or stick on 5? As far as I can tell it is backwards compatible.

**Comment by jeffw16** [comment]
Nope, our web host does not have PHP 7... yet.

**Comment by jeffw16** [comment]
For purposes of compatibility with most web servers, we should officially stick with older coding practices found in PHP 5. Although PHP 7 is mostly backwards-compatible with PHP 5.6, in case of a code conflict between PHP 5.6 and 7 (i.e. PHP 5.6 and 7 do something differently and there is no way to satisfy both), PHP 5.6 will prevail. Those conflicts should be documented in a file when the issue arises.

This situation will probably change in the near future. When most web hosts adopt PHP 7 as the norm, I'd be happy to drop support for 5.6 and move to PHP 7.
